### ISSUE TITLE
.babelrc and .eslintrc.js not picked up?

### ISSUE THREAD

**Issue by Ruudieboy** [evanshortiss/s2i-nodejs-nginx-example#1]
Thanks for your amazing work on this! Very useful.

I am having some issues to get it working in my own project. It seems like the .babelrc and .eslintrc.js files are not being picked up, which causes my build to fail. Do you have any idea what might cause this? Is it possible that the '.' files are not being copied?

**Comment by Ruudieboy** [comment]
Apparently dot files are not being moved with the `mv` command. Found an answer over here: https://stackoverflow.com/questions/49847803/use-a-real-git-repo-during-an-openshift-build
This also causes that a custom nginx.conf is not being found.

Would be nice if this can be included in the base image since so many projects use dotfiles.

**Comment by evanshortiss** [comment]
@Ruudieboy for some reason this never appeared in my notifications. Sorry about that.

Did you get it working in the end. I'm happy to accept a PR, bit short on time at the moment to get around to it.

**Comment by evanshortiss** [comment]
Just checking back on this sample repo since I updated the builder image. I believe this issue is addressed in https://github.com/evanshortiss/s2i-nodejs-nginx/commit/1bdf7be7f9a7bc1e32666db8e52481e9a76d071c
